### ISSUE TITLE
py3 compatibility issue

### ISSUE THREAD

**Issue by easyw** [realthunder/fcad_pcb#10]
I've tested the tools in 
[FreeCAD_0.18.14928_Conda_Py3QT5-WinVS2015_x64.7z](https://github.com/FreeCAD/FreeCAD/releases/download/0.18_pre/FreeCAD_0.18.14928_Conda_Py3QT5-WinVS2015_x64.7z)
and I get the following errors:

> Traceback (most recent call last):
  File "...../fcad_pcb-test.py", line 22, in <module>
    from fcad_pcb import kicad
  File ".....\fcad_pcb\kicad.py", line 18, in <module>
    from kicad_parser import KicadPCB,SexpList
  File ".....\fcad_pcb\kicad_parser\__init__.py", line 1, in <module>
    from kicad_pcb import *
<class 'ModuleNotFoundError'>: No module named 'kicad_pcb'

**Comment by realthunder** [comment]
I've just added support of Python3. Please sync the repo along with all the sub modules.

**Comment by easyw** [comment]
Thx 😄
