### ISSUE TITLE
PCB with a rounded corners

### ISSUE THREAD

**Issue by yrabbit** [realthunder/fcad_pcb#13]
Hello, 
I'm trying to make a circuit board with rounded corners, but makeBoard() call leads to this very strange result. Am I missing some critical parameter?
The project files are very simple but I attach them anyway.

![freecad](https://user-images.githubusercontent.com/6075465/54584042-effb0780-4a61-11e9-9170-8764639d5920.png)
![kicad](https://user-images.githubusercontent.com/6075465/54584043-effb0780-4a61-11e9-85cd-4f686adbdd49.png)
[kicad-round-corners.zip](https://github.com/realthunder/fcad_pcb/files/2981800/kicad-round-corners.zip)
[freecad-round-corners.zip](https://github.com/realthunder/fcad_pcb/files/2981803/freecad-round-corners.zip)

**Comment by realthunder** [comment]
Bug fixed. Thanks for reporting!
