### ISSUE TITLE
missing support for (recently added) bspline in pcb Edge-Cuts

### ISSUE THREAD

**Issue by easyw** [realthunder/fcad_pcb#16]
It seems that KiCAD has added support for Bspline (not with a direct editing, but importing from an external dxf)
the format is as following:
`(gr_curve (pts (xy 126.405224 109.822162) (xy 126.619375 110.505073) (xy 126.940067 111.113882) (xy 127.36623 111.622109)) (layer Edge.Cuts) (width 0.2))`
a sample board here:
https://gitlab.com/morganrallen/kickbadge/blob/development/kickbadge.kicad_pcb
coming from this DXF
https://gitlab.com/morganrallen/kickbadge/blob/development/kickstarter.dxf

**Comment by realthunder** [comment]
Just implemented. Please test.

**Comment by easyw** [comment]
I can confirm it is working! 
Thx 😄
