### ISSUE TITLE
KiCAD quoted layer names

### ISSUE THREAD

**Issue by yrabbit** [realthunder/fcad_pcb#18]
Hello
    More recent Kicad_pcb files have quoted layer names (i.e. strings, not symbols). The importer doesn't handle that, so it doesn't see elements like (layer "Edge.Cuts").

Here are the old and new files of almost the same board.
[pcbs.zip](https://github.com/realthunder/fcad_pcb/files/3375575/pcbs.zip)

**Comment by realthunder** [comment]
Fixed. Please check.

**Comment by yrabbit** [comment]
Thanks! Works like a charm:)
