### ISSUE TITLE
missing support for Taper footprint

### ISSUE THREAD

**Issue by easyw** [realthunder/fcad_pcb#21]
Hi,
would please have a look to this board?
[flex-kicad_pcb.zip](https://github.com/realthunder/fcad_pcb/files/4190840/flex-kicad_pcb.zip)
The board has taper footprints, built having pad inside a polyline pad (this is done to have DRC and connectivity behavior).
The taper fp is not loaded correctly.
Thanks in advance.

**Comment by realthunder** [comment]
I did quick fix. Please check.

**Comment by easyw** [comment]
it works like a charm... thx for the fix :)
