### ISSUE TITLE
Add support for oval holes; Add support for blind/micro vias

### ISSUE THREAD

**Issue by MitjaNemec** [realthunder/fcad_pcb#23]
Hi!

I really appreciate your work done so far. So I humbly ask if you could:
1. Add support for oval holes
2. Add support for micro/blind vias

Thanks in advance

I am attaching a test project with the screenshot how the macro behave currently (tested with 5cd7951c51767cb5831e33420846055d10454d62 on KiCad 5.1.5-90-g5c7ac1bb7(current nightly) an FreeCad 18.4.
Executed code:
``` python
from fcad_pcb import kicad
pcb = kicad.KicadFcad("D:/Mitja/Plate/ACS_fcad_pcb_test/ACS_fcad_pcb_test.kicad_pcb")
pcb.make(copper_thickness=0.070, board_thickness=1.32, combo=False, fuseCoppers=True )
```

KiCad 3D view, board and soldermask not shown:
![image](https://user-images.githubusercontent.com/18001294/79116627-4c297b80-7d89-11ea-98d4-4721bb8ff188.png)
FreeCad 3D view, board hidden:
![image](https://user-images.githubusercontent.com/18001294/79116672-6c593a80-7d89-11ea-96f5-f585bc40c1f3.png)

KiCad project
[ACS_fcad_pcb_test.zip](https://github.com/realthunder/fcad_pcb/files/4469295/ACS_fcad_pcb_test.zip)

**Comment by realthunder** [comment]
Added, please check. BTW, oval hole should be working with you current version. Not sure why it didn't work in your place. Can you please download the latest FC 0.19 dev and try?

**Comment by MitjaNemec** [comment]
I can confirm that blind/micro vias work. But the oval hole is not working. Neither in 0.18.4 nor in 0.19.20514-Win-Conda_vc14.x-x86_64
![image](https://user-images.githubusercontent.com/18001294/79308754-7bf79100-7ef9-11ea-8227-789bf2c5964e.png)

**Comment by easyw** [comment]
@realthunder 
I confirm to have the same issue with the test file provided.

**Comment by realthunder** [comment]
Should be fixed by now. You'll need to update the submodules recursively with
```
git submodule update --recursive
```

**Comment by MitjaNemec** [comment]
Confirming. Works as it should.

Again thank you for your support.

**Comment by easyw** [comment]
+1
thanks 😺
