### ISSUE TITLE
Missing oval pads

### ISSUE THREAD

**Issue by 9robs** [realthunder/fcad_pcb#25]
Commenting based on this KiCAD forum thread:
https://forum.kicad.info/t/export-only-trace-vias-as-3d-model/22683/5

I LOVE this tool - thank you so much for developing it...but in a board I am trying to import it seems the oval pads are not being created...Any hints? What am I missing?

![image](https://user-images.githubusercontent.com/24436837/81108813-cbb8ef00-8ede-11ea-8067-5f8636d513ec.png)

![image](https://user-images.githubusercontent.com/24436837/81108835-d2476680-8ede-11ea-9649-acb92f8fd4f7.png)

**Comment by realthunder** [comment]
Is is possible to provide a sample file for this problem?

**Comment by 9robs** [comment]
Attached - there is a lot going on with this board and it is not anything 'real'...just more for R&D purposes (imported from Eagle)....if you would like a simpler version with the same issue, let me know...
[demo3.zip](https://github.com/realthunder/fcad_pcb/files/4589642/demo3.zip)

**Comment by realthunder** [comment]
Fixed. Please check.

**Comment by 9robs** [comment]
Works like a charm - much appreciated...where should I send the "thank you" beers

**Comment by realthunder** [comment]
You can click any donation badge [here](https://github.com/realthunder/FreeCAD_assembly3#assembly3-workbench-for-freecad). Thanks!

Maybe you will also be interested to follow my FreeCAD development there.
