### ISSUE TITLE
missing support for (recently added) rectangle in pcb geometry

### ISSUE THREAD

**Issue by easyw** [realthunder/fcad_pcb#26]
recently rectangle has been added in pcb geometry
[menubar_pcb_editor.cpp#L417](https://gitlab.com/kicad/code/kicad/-/blob/7b042f4a75bc99256b31d4840a5af4f9c5fe1bc5/pcbnew/menubar_pcb_editor.cpp#L417)
`  (gr_rect (start 52.9 59.7) (end 200 130.9) (layer "Edge.Cuts") (width 0.05) (tstamp a3f0bd33-c126-463e-b7da-fa8ba45c650e))
`
I'm attaching a sample board
[rectangle-kv6.zip](https://github.com/realthunder/fcad_pcb/files/4862814/rectangle-kv6.zip)

**Comment by realthunder** [comment]
Implemented. Please check.

**Comment by easyw** [comment]
thx
