### ISSUE TITLE
Feature request:  import pcb stackup information automatically

### ISSUE THREAD

**Issue by sslupsky** [realthunder/fcad_pcb#41]
Kicad 5.99 now has support for the pcb stackup.  Could your macro be modified to import the copper thickness and dielectric materials and thickness for each layer from the pcb stackup?

**Comment by realthunder** [comment]
The feature has been implemented. When making the board, do not supply any thickness parameter. The script will use the stackup info if it's available, or else supply with default thickness. Please try and report any problem with a sample file showing the problem. Thanks!
