### ISSUE TITLE
no module named fcad_pcb

### ISSUE THREAD

**Issue by robotfishe** [realthunder/fcad_pcb#50]
This might be a really simple problem, but I've been unable to fix it on two Windows PCs and one Ubuntu one. I follow the instructions to clone the repositories and check out the submodules into my macros directory, so I have an fcad_pcb directory inside my macro directory with kicad.py, kicad_parser, etc inside that.

When I try entering "from fcad_pcb import kicad" in the python console in FreeCAD, I get the following error:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\FreeCAD\bin\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'fcad_pcb'

Any ideas?

**Comment by realthunder** [comment]
Maybe you didn't get the correct Macro directory?

![Screenshot from 2021-11-13 06-58-00](https://user-images.githubusercontent.com/1207888/141590081-a4f846ae-8a84-4c48-8e03-d31f5ab90088.png)

**Comment by robotfishe** [comment]
Nope, it's definitely not that:

![fcad1](https://user-images.githubusercontent.com/64608682/141593725-1ee18166-b6ef-496c-9a13-799df5a2881e.png)
![fcad2](https://user-images.githubusercontent.com/64608682/141593726-439b2498-1f9a-4559-ad1a-33140aaba4ec.png)
![fcad3](https://user-images.githubusercontent.com/64608682/141593724-4930d0f0-fda9-4ccb-85bd-e76e07e7daff.png)

**Comment by realthunder** [comment]
Ah, I see it. You miss spell the module name. Should be `fcad_pcb`. `fcad` is short for `FreeCAD`.

**Comment by robotfishe** [comment]
Oops, made a typo that time, but I get the same error when it's spelled correctly.

![fcad3](https://user-images.githubusercontent.com/64608682/141596521-93db030f-2590-469c-9404-0d750299d117.png)

**Comment by realthunder** [comment]
That's strange. Have you ever tried other macros? Do they work? Can you find your macro directory in `sys.path`?

```
import sys
sys.path
```

**Comment by robotfishe** [comment]
Running sys.path was helpful in a weird way! The macros directory under AppData was there, but I also noticed that there was another Macros path listed, C:\\Program Files\\FreeCAD\\Macros. I copied fcad_pcb into there, restarted FreeCAD, and suddenly I'm able to import.

Still no idea why it was failing to pick up from the correct place, though.

**Comment by realthunder** [comment]
Maybe some permission issue.
