### ISSUE TITLE
kicad 6 stackup issue on load tracks

### ISSUE THREAD

**Issue by easyw** [realthunder/fcad_pcb#57]
adding tracks with custom kicad stackup is failing
I'm attaching a sample board
[stackup-issue-saved-test.zip](https://github.com/realthunder/fcad_pcb/files/9106018/stackup-issue-saved-test.zip)
(tested with FC0.20 and 0.21)

PS in which way it is possible to enable the logging and where does it writes a lo file?

**Comment by realthunder** [comment]
The logger simply prints to FreeCAD console.

**Comment by easyw** [comment]
> The logger simply prints to FreeCAD console.

thanks, that was easy 😸

**Comment by easyw** [comment]
and with the latest commit https://github.com/realthunder/fcad_pcb/commit/d3d4727eeeb09073290c9101833e4f275f1ec92c, the script doesn't work anymore with kv5 pcb files, where stackup is not present.
