### ISSUE TITLE
No module named future.utils

### ISSUE THREAD

**Issue by traveler787** [realthunder/fcad_pcb#6]
I am getting an error from kicad.py line 4.  It says "No module named future.utils"

I cloned the repo to C:\Users\30920\AppData\Roaming\FreeCAD\Macro\fcad_pcb
and checked out the submodules.

Here is my contents of fcad_pcb
----------------
.git
kicad_parser
screenshots
tests
.gitignore
.gitmodules
__init__.py
__init__.pyc
kicad.py
kicad.pyc
LICENSE
Readme.md
----------------

Any help would be appreciated.
Brian

**Comment by realthunder** [comment]
Which platform are you in? Future is a standard python module, and can be installed with pip.

**Comment by traveler787** [comment]
I am on Windows 10.  I suspected that was what I needed.  With some more searching I found how to install the Future module...

Open an administrative command prompt at the FreeCAD bin directory (ie.  C:\Program Files\FreeCAD 0.17\bin)
Run "python -m pip install future"

Is the script able to generate solder mask or silk screen layers, or load 3D components?

Very nice script.  Thank you.

**Comment by realthunder** [comment]
Solder mask and silk screen are not supported yet. Loading of 3D components is probably broken with the current version of FreeCAD. You can try the [StepUp](https://www.freecadweb.org/wiki/KicadStepUp_Workbench/it) workbench. You can install it using FreeCAD addon manager.

**Comment by traveler787** [comment]
Thank you again.
