### ISSUE TITLE
Zone not imported if zone active for multiple layers

### ISSUE THREAD

**Issue by aa956** [realthunder/fcad_pcb#66]
Zone will not be imported if zone is active for both F.Cu and B.Cu layers.
Probably other combination of layers (F, B, In.1, In.2 etc will be affected too):

![image](https://user-images.githubusercontent.com/27946957/231087634-61147a27-d010-45c7-9e58-c2d36fc3ecaf.png)

Zones are successfully imported if there are 2 zones (duplicates of each other), one of them only in F.Cu, other only in B.Cu

**Comment by realthunder** [comment]
Could you please provide a sample file for this?

**Comment by aa956** [comment]
Attached the KiCAD example project.

Recreated with freshly reinstalled KiCAD 7.0.10, tried to import in fresh FreeCAD 0.21.2 install with newly checked out master branch of fcad_pcb (currently f413e02c36fbcd73165992b800e235ac49117228):

Still the same issue, looks like PCB multi layer zone (`(layers "F&B.Cu")` in the attached project) is problematic:

```
(zone (net 2) (net_name "GND") (layers "F&B.Cu") (tstamp 25dbf940-302e-4dc3-8b7b-d484cd6cc2da) (name "global_gnd") (hatch edge 0.5)
```
[copper_area_issue66.zip](https://github.com/realthunder/fcad_pcb/files/14154231/copper_area_issue66.zip)
