### ISSUE TITLE
How to create a drilling operation easily?

### ISSUE THREAD

**Issue by yrabbit** [realthunder/fcad_pcb#8]
Hello,
I have a naive question. I have a Kicad file with a board that contains about 130 holes. I know that one can auto create Path Drilling Object in Path WB from features of a job base object.

If I create a job with a board_solid # F.Cu as the base object, then the holes are not found automatically.
I can add each hole with the mouse, but I'm afraid of making a mistake and skipping something.

**Comment by realthunder** [comment]
You can expand the solid object, and find the hole wire object named holes_wire#F.Cu. Extrude that wire, and use this as base object for drilling.

You can also filter hole size. For example, to get the wire for 0.8mm holes,

```
pcb.makeHoles(minSize=0.8)
```

**Comment by yrabbit** [comment]
Thanks :)
