### ISSUE TITLE
A mistype in the wiki

### ISSUE THREAD

**Issue by yrabbit** [realthunder/fcad_pcb#9]
Hello,
there is a little mistype at https://github.com/realthunder/FreeCAD_assembly3/wiki/Build-Instruction 

The line ``After finish, copy slvs.py and _slvs.pyd from asm3/slvs/build/src/swig/python/CMakeFiles'' has a superfluous directory /CMakeFiles.

**Comment by realthunder** [comment]
Thanks for the report! Fixed.
